"""
파일 내보내기 라우터
====================
생성된 코드를 ZIP 파일로 압축하여 다운로드합니다.
배포에 필요한 scaffolding 파일도 자동 포함합니다.
"""

import io
import json
import zipfile

from fastapi import APIRouter
from fastapi.responses import StreamingResponse
from pydantic import BaseModel

router = APIRouter(prefix="/api", tags=["export"])


class ExportFile(BaseModel):
    path: str
    code: str
    language: str = "tsx"


class ExportRequest(BaseModel):
    project_name: str = "my-project"
    files: list[ExportFile]


# ──────────────────────────────────────────────
# 배포용 Scaffolding 파일 생성
# ──────────────────────────────────────────────
def _make_package_json(name: str, has_backend: bool) -> str:
    pkg = {
        "name": name,
        "version": "1.0.0",
        "private": True,
        "scripts": {
            "dev": "next dev",
            "build": "next build",
            "start": "next start",
            "lint": "next lint",
        },
        "dependencies": {
            "next": "^14.2.0",
            "react": "^18.3.0",
            "react-dom": "^18.3.0",
        },
        "devDependencies": {
            "@types/node": "^20",
            "@types/react": "^18",
            "@types/react-dom": "^18",
            "typescript": "^5",
            "tailwindcss": "^3.4.0",
            "postcss": "^8",
            "autoprefixer": "^10",
        },
    }
    return json.dumps(pkg, indent=2, ensure_ascii=False)


TSCONFIG = """{
  "compilerOptions": {
    "target": "ES2017",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [{ "name": "next" }],
    "paths": { "@/*": ["./src/*"] }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}"""

NEXT_CONFIG = """/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  images: {
    domains: [],
    unoptimized: true,
  },
  typescript: {
    ignoreBuildErrors: true,
  },
  eslint: {
    ignoreDuringBuilds: true,
  },
};

module.exports = nextConfig;
"""

TAILWIND_CONFIG = """/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
};
"""

POSTCSS_CONFIG = """module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};
"""

GITIGNORE = """# dependencies
/node_modules
/.pnp
.pnp.js

# testing
/coverage

# next.js
/.next/
/out/

# production
/build

# misc
.DS_Store
*.pem
.env
.env*.local

# debug
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# typescript
*.tsbuildinfo
next-env.d.ts
"""

GLOBAL_CSS = """@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  --foreground-rgb: 0, 0, 0;
  --background-start-rgb: 255, 255, 255;
  --background-end-rgb: 255, 255, 255;
}

body {
  color: rgb(var(--foreground-rgb));
  background: linear-gradient(
    to bottom,
    rgb(var(--background-start-rgb)),
    rgb(var(--background-end-rgb))
  );
  font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
}
"""

LAYOUT_TSX = """import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: '%PROJECT_NAME%',
  description: 'Generated by Agentic Web Builder',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body>{children}</body>
    </html>
  );
}
"""

VERCEL_JSON = """{
  "framework": "nextjs",
  "buildCommand": "next build",
  "outputDirectory": ".next"
}
"""

ENV_EXAMPLE = """# 환경 변수 예시
# 실제 값으로 교체하세요
NEXT_PUBLIC_API_URL=http://localhost:8000
"""

DOCKERFILE = """FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./
COPY --from=builder /app/public ./public

EXPOSE 3000
CMD ["npm", "start"]
"""


@router.post("/export/zip")
async def export_zip(request: ExportRequest):
    """생성된 코드를 배포 가능한 프로젝트 ZIP으로 내보내기"""
    zip_buffer = io.BytesIO()
    name = request.project_name

    # 백엔드 파일이 있는지 체크
    has_backend = any(
        f.language in ("python", "py") or f.path.endswith(".py")
        for f in request.files
    )

    # 이미 포함된 파일 경로 목록
    existing_paths = {f.path for f in request.files}

    with zipfile.ZipFile(zip_buffer, "w", zipfile.ZIP_DEFLATED) as zf:
        # 생성된 코드 파일
        for f in request.files:
            zf.writestr(f.path, f.code)

        # ── Scaffolding 파일 자동 추가 (없는 경우만) ──
        scaffolds = {
            "package.json": _make_package_json(name, has_backend),
            "tsconfig.json": TSCONFIG,
            "next.config.js": NEXT_CONFIG,
            "tailwind.config.js": TAILWIND_CONFIG,
            "postcss.config.js": POSTCSS_CONFIG,
            ".gitignore": GITIGNORE,
            "vercel.json": VERCEL_JSON,
            ".env.example": ENV_EXAMPLE,
            "Dockerfile": DOCKERFILE,
        }

        # globals.css가 없으면 추가
        if "src/app/globals.css" not in existing_paths:
            scaffolds["src/app/globals.css"] = GLOBAL_CSS

        # layout.tsx가 없으면 추가
        if "src/app/layout.tsx" not in existing_paths:
            scaffolds["src/app/layout.tsx"] = LAYOUT_TSX.replace("%PROJECT_NAME%", name)

        for path, content in scaffolds.items():
            if path not in existing_paths:
                zf.writestr(path, content)

        # README 자동 생성
        readme = f"# {name}\n\n"
        readme += "> 이 프로젝트는 **Agentic Web Builder**에 의해 자동 생성되었습니다.\n\n"
        readme += "## 시작하기\n\n"
        readme += "```bash\n"
        readme += "npm install\n"
        readme += "npm run dev\n"
        readme += "```\n\n"
        readme += "브라우저에서 [http://localhost:3000](http://localhost:3000)으로 접속하세요.\n\n"
        readme += "## Vercel 배포\n\n"
        readme += "```bash\n"
        readme += "npx vercel\n"
        readme += "```\n\n"
        readme += "## 파일 구조\n\n"
        readme += "| 파일 | 언어 |\n"
        readme += "|------|------|\n"
        for f in request.files:
            readme += f"| `{f.path}` | {f.language} |\n"
        readme += "\n## 기술 스택\n\n"
        readme += "- **Next.js 14** — React 풀스택 프레임워크\n"
        readme += "- **Tailwind CSS 3** — 유틸리티 CSS\n"
        readme += "- **TypeScript** — 타입 안전성\n"
        if has_backend:
            readme += "- **Python/FastAPI** — 백엔드 API\n"

        zf.writestr("README.md", readme)

    zip_buffer.seek(0)

    return StreamingResponse(
        zip_buffer,
        media_type="application/zip",
        headers={
            "Content-Disposition": f"attachment; filename={name}.zip",
        },
    )
